# Use postgres/example user/password credentials
version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - postgres.env # configure Postgres
    volumes:
      - ./_postgresql-data:/var/lib/postgresql/data/ # persist data even if the container shuts down
    ports:
      - "15432:5432" # disable this if you don't wish to access Postgres from the docker host, port 15432

  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080 # disable this if you don't wish to access the service on docker host, port 18080
